### ISSUE TITLE
ITCH

### ISSUE THREAD

**Issue by saltzmanjoelh** [Nasdaq/nasdaq-protocols#7]
Hi, I'm looking to try out using the ITCH protocol to get stock pricing data from Nasdaq to build some arbitrage trading tools. Do you have any recommendations on getting started with ITCH?

**Comment by SamDanielThangarajan** [comment]
Refer to documentation here https://nasdaq.github.io/nasdaq-protocols/

**Comment by joelatgrayv** [comment]
Thank you!

**Comment by saltzmanjoelh** [comment]
Thank you
